version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app
    depends_on:
      - mysql
    env_file:
      - ./api/.env
    ports:
      - "4000:4000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    environment:
      REACT_APP_CONTAINER: Docker
    depends_on:
      - api
    ports:
      - "3000:3000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "81:80"
    depends_on:
      - client
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  dbdata:
    driver: local
